'use client';
import { useEffect, useRef, useState } from 'react';
import { ImagePlus, Download, Play, Square, Brain, ScanText, Check, Trash2 } from 'lucide-react';
import { acceptSnapshot, callNative, cancelNative, isDesktop, nativeOperation, persistNative, pickNativeFile, type NativeSnapshot } from '@/lib/specimen/native';
import type { Specimen } from '@/lib/specimen/types';
interface Model {id:string;name:string;kind:string;size:number;source:string;license:string;revision:string;sha256:string;memoryBytes:number}
interface Installed {model:Model;installed:boolean;loaded:boolean}
interface Analysis {width:number;height:number;patternId:string;resolution:string;contours:number[][];holes:number;convex:number;concave:number;ocr:{text:string;regions:{cx:number;cy:number;width:number;height:number}[]}[];ocrStatus:string;features:number[];sdf:{values:number[]};focus:{x:number;y:number;width:number;height:number}}
interface Analyzed {analysis:Analysis;asset:string;matches:{name:string;score:{confidence:number}}[]}
interface Artifact {id:string;model:string;text?:string;asset?:string;prompt:string;seed:number;modelDigest:string;createdAt:string}
export function NativeLab({specimen,onSnapshot}:{specimen:Specimen;onSnapshot:(s:Specimen)=>void}){
 const [desktop,setDesktop]=useState(false),[models,setModels]=useState<Installed[]>([]),[busy,setBusy]=useState(''),[status,setStatus]=useState(''),[error,setError]=useState(''),[image,setImage]=useState(''),[analysis,setAnalysis]=useState<Analyzed|null>(null),[ocr,setOcr]=useState(''),[name,setName]=useState(''),[prompt,setPrompt]=useState(''),[kind,setKind]=useState('qwen3-4b'),[seed,setSeed]=useState(104729),[artifacts,setArtifacts]=useState<Artifact[]>([]),[focus,setFocus]=useState({x:0,y:0,width:1,height:1});
 const [activeJobs,setActiveJobs]=useState<string[]>([]),[aspect,setAspect]=useState(4/3);
 const file=useRef<HTMLInputElement>(null),bytes=useRef<number[]>([]),job=useRef(''),imageRef=useRef('');
 const refresh=async()=>{setActiveJobs(await callNative<string[]>({op:'jobs'}));const response=await callNative<Installed[]|{busy:true}>({op:'models'});if(Array.isArray(response))setModels(response);};
 useEffect(()=>{setDesktop(isDesktop());if(!isDesktop())return;void refresh().catch(e=>setError(e.message));void callNative<NativeSnapshot>({op:'snapshot'}).then(s=>setArtifacts(s.artifacts as unknown as Artifact[]));const timer=setInterval(()=>void refresh().catch(()=>{}),5000);return()=>clearInterval(timer);},[]);
 useEffect(()=>()=>URL.revokeObjectURL(imageRef.current),[]);
 const progress=(event:Record<string,unknown>)=>{setStatus(typeof event.received==='number'&&typeof event.total==='number'?`${event.phase}: ${Math.round(100*event.received/event.total)}%`:String(event.phase??'Working…'));};
 const work=async(label:string,fn:()=>Promise<void>)=>{if(busy)return;job.current=crypto.randomUUID();setBusy(label);setError('');setStatus(label);try{await fn();setStatus('Completed');}catch(e){setError(e instanceof Error?e.message:String(e));setStatus('Stopped');}finally{setBusy('');job.current='';void refresh().catch(()=>{});}};
 const snapshot=(s:NativeSnapshot)=>{const latest=acceptSnapshot(s);if(latest.specimen)onSnapshot(latest.specimen);setArtifacts(latest.artifacts as unknown as Artifact[]);};
 const choose=async(selected?:File)=>{if(!selected)return;if(selected.size>32*1024*1024){setError('Choose an image under 32 MB.');return;}bytes.current=Array.from(new Uint8Array(await selected.arrayBuffer()));URL.revokeObjectURL(imageRef.current);imageRef.current=URL.createObjectURL(selected);setImage(imageRef.current);setName(selected.name.replace(/\.[^.]+$/,''));setAnalysis(null);setFocus({x:0,y:0,width:1,height:1});};
 const analyze=()=>work('Analyzing image',async()=>{const result=await nativeOperation<Analyzed>({op:'analyze',bytes:bytes.current,focus,jobId:job.current},progress);setAnalysis(result);setOcr(result.analysis.ocr.map(x=>x.text).join('\n'));});
 const learn=()=>work('Learning image',async()=>{if(!analysis)return;await persistNative(specimen);snapshot(await nativeOperation<NativeSnapshot>({op:'learnVisual',asset:analysis.asset,analysis:analysis.analysis,name,ocrCorrection:ocr}));});
 const runImage=()=>work('Running image cycle',async()=>{if(!analysis)return;await persistNative(specimen);const result=await nativeOperation<{snapshot:NativeSnapshot}>({op:'runVisual',asset:analysis.asset,focus,jobId:job.current},progress);snapshot(result.snapshot);});
 const runOcr=()=>work('Running recognized text',async()=>{await persistNative(specimen);const result=await nativeOperation<{snapshot:NativeSnapshot}>({op:'run',input:ocr,jobId:job.current},progress);snapshot(result.snapshot);});
 const install=(id:string,fromFile=false)=>work('Installing model',async()=>{let path:string|undefined;if(fromFile){path=await pickNativeFile();if(!path)return;}await nativeOperation({op:'installModel',modelId:id,path,jobId:job.current},progress);});
 const generate=()=>work('Generating locally',async()=>{await persistNative(specimen);const result=await nativeOperation<{snapshot:NativeSnapshot;artifact:Artifact}>({op:'generate',modelId:kind,prompt,seed,jobId:job.current},progress);snapshot(result.snapshot);});
 const learnText=(artifact:Artifact)=>work('Learning generated text',async()=>{await persistNative(specimen);snapshot(await nativeOperation<NativeSnapshot>({op:'learnText',artifactId:artifact.id}));});
 const learnOcr=()=>work('Learning reviewed text',async()=>{if(!analysis)return;await persistNative(specimen);snapshot(await nativeOperation<NativeSnapshot>({op:'learnText',asset:analysis.asset,pattern:name,text:ocr}));});
 if(!desktop)return <section className="panel native-intro"><Brain size={30}/><h2>Bring your specimen to the desktop</h2><p>The desktop edition adds image analysis, local OCR, a fixed sparse network, and local text and image models. Your browser specimen continues to run here with browser storage.</p><p>Use Save specimen to transfer your current patterns to the desktop app.</p><div className="runtime-pills"><span>Browser runtime</span><span>Local browser storage</span><span>Text patterns</span></div></section>;
 return <div className="native-lab"><div className="runtime-pills"><span><Check size={13}/> Native Rust engine</span><span>WDBX transactional storage</span><span>Local processing</span></div><div className="lab-status" role="status">{status||'Ready to inspect or compose'}{busy&&<button className="btn secondary" onClick={()=>void cancelNative(job.current)}><Square size={13}/>Cancel</button>}</div>{activeJobs.filter(id=>id!==job.current).map(id=><div className="lab-status" key={id}>Desktop job in progress<button className="btn secondary" onClick={()=>void cancelNative(id)}>Cancel job</button></div>)}{error&&<div className="error-banner" role="alert">{error}</div>}
 <div className="lab-grid"><section className="panel lab-panel"><div className="panel-heading"><div><h2><ImagePlus size={18}/> Image workspace</h2><p>Drop an image, move the focus, then inspect its features.</p></div><button className="btn secondary" disabled={!!busy} onClick={()=>file.current?.click()}>Open image</button></div><input ref={file} type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={e=>void choose(e.target.files?.[0])}/>
 <div className="image-workspace" style={{aspectRatio:aspect}} tabIndex={0} aria-label="Image drop and focus workspace" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void choose(e.dataTransfer.files[0]);}} onPaste={e=>{const f=Array.from(e.clipboardData.files)[0];if(f){e.preventDefault();void choose(f);}}} onClick={e=>{if(!image||busy)return;const r=e.currentTarget.getBoundingClientRect();setFocus(f=>({...f,x:Math.max(0,Math.min(1-f.width,(e.clientX-r.left)/r.width-f.width/2)),y:Math.max(0,Math.min(1-f.height,(e.clientY-r.top)/r.height-f.height/2))}));setAnalysis(null);}}>
 {image?<><img src={image} alt="Original image for analysis" onLoad={e=>setAspect(e.currentTarget.naturalWidth/e.currentTarget.naturalHeight)} style={{filter:focus.width<1?'blur(3px)':'none'}}/><img src={image} alt="Focused image region" style={{position:'absolute',inset:0,clipPath:`inset(${focus.y*100}% ${(1-focus.x-focus.width)*100}% ${(1-focus.y-focus.height)*100}% ${focus.x*100}%)`}}/><div className="focus-frame" style={{left:`${focus.x*100}%`,top:`${focus.y*100}%`,width:`${focus.width*100}%`,height:`${focus.height*100}%`}}/>{analysis&&<svg className="contour-overlay" viewBox="0 0 100 100" preserveAspectRatio="none">{analysis.analysis.contours.map(([x,y],i)=><circle key={i} cx={(focus.x+x*focus.width)*100} cy={(focus.y+y*focus.height)*100} r=".25" fill="#ebae44"/>)}{analysis.analysis.ocr.flatMap((line,li)=>line.regions.map((region,ri)=><rect key={`ocr-${li}-${ri}`} x={(focus.x+(region.cx-region.width/2)/analysis.analysis.width)*100} y={(focus.y+(region.cy-region.height/2)/analysis.analysis.height)*100} width={region.width/analysis.analysis.width*100} height={region.height/analysis.analysis.height*100} fill="none" stroke="#3786aa" strokeWidth=".25"><title>{line.text}</title></rect>))}</svg>}</>:<div className="image-placeholder"><ImagePlus size={38}/><strong>Drop or paste an image here</strong><span>PNG, JPEG or WebP · up to 32 MB</span></div>}</div>
 <label className="lab-field">Focus size<input type="range" min="20" max="100" value={focus.width*100} disabled={!!busy} onChange={e=>{const size=Number(e.target.value)/100;setFocus(f=>({...f,width:size,height:size,x:Math.min(f.x,1-size),y:Math.min(f.y,1-size)}));setAnalysis(null);}}/></label><button className="btn primary" onClick={()=>void analyze()} disabled={!image||!!busy}><ScanText size={15}/>Analyze image & OCR</button>
 {analysis&&<div className="analysis-result"><code>{analysis.analysis.patternId}</code><p>{analysis.analysis.resolution} complexity · {analysis.analysis.contours.length} boundary points · {analysis.analysis.holes} holes</p><p>{analysis.analysis.ocrStatus}</p><label className="lab-field">Recognized text · edit before learning<textarea value={ocr} onChange={e=>setOcr(e.target.value)} rows={3}/></label><label className="lab-field">Pattern name<input value={name} onChange={e=>setName(e.target.value)}/></label><button className="btn primary" disabled={!!busy||!name.trim()} onClick={()=>void learn()}>Learn this image</button><button className="btn secondary" disabled={!!busy} onClick={()=>void runImage()}>Run image cycle</button><button className="btn secondary" disabled={!!busy||!ocr.trim()} onClick={()=>void runOcr()}>Run recognized text</button><button className="btn secondary" disabled={!!busy||!ocr.trim()||!name.trim()} onClick={()=>void learnOcr()}>Learn reviewed text</button>{analysis.matches.length>0&&<ul>{analysis.matches.map((m,i)=><li key={i}>{m.name} · {m.score.confidence.toFixed(1)} confidence</li>)}</ul>}<details><summary>Feature and signed-distance evidence</summary><pre>{JSON.stringify({features:analysis.analysis.features,sdfRange:[Math.min(...analysis.analysis.sdf.values),Math.max(...analysis.analysis.sdf.values)],convex:analysis.analysis.convex,concave:analysis.analysis.concave},null,2)}</pre></details></div>}
 </section><section className="panel lab-panel"><div className="panel-heading"><div><h2><Brain size={18}/> Local generation</h2><p>Compose with installed models. Learning remains explicit.</p></div></div><label className="lab-field">Model<select value={kind} onChange={e=>setKind(e.target.value)}><option value="qwen3-4b">Qwen3 4B · text</option><option value="sdxl-turbo">SDXL Turbo · image</option></select></label><label className="lab-field">Prompt<textarea value={prompt} onChange={e=>setPrompt(e.target.value)} maxLength={8000} rows={5} placeholder="Describe what you want to compose…"/></label><label className="lab-field">Seed<input type="number" min={0} max={2147483647} value={seed} onChange={e=>setSeed(Math.max(0,Math.min(2147483647,Number(e.target.value))))}/></label><button className="btn primary" disabled={!!busy||!prompt.trim()||!models.find(m=>m.model.id===kind)?.installed} onClick={()=>void generate()}><Play size={14}/>Generate locally</button>
 <h3 className="model-heading">Installed models</h3>{models.map(({model,installed,loaded})=><article className="model-card" key={model.id}><div><strong>{model.name}</strong><span className="model-state">{loaded?'Loaded':installed?'Installed':'Not installed'} · {(model.size/1024/1024).toFixed(0)} MB</span></div><p>{model.license}</p><p>{model.memoryBytes?`${(model.memoryBytes/1e9).toFixed(1)} GB available memory estimated`:'Loads for each analysis'}</p><details><summary>Source & verification</summary><a href={model.source} target="_blank" rel="noreferrer">Publisher model card</a><code>{model.revision}</code><code>{model.sha256}</code></details><div className="model-actions">{!installed?<><button className="btn secondary" disabled={!!busy} onClick={()=>void install(model.id)}><Download size={13}/>Download</button><button className="btn secondary" disabled={!!busy} onClick={()=>void install(model.id,true)}>Import file</button></>:<button className="btn secondary" disabled={!!busy} onClick={()=>void work('Removing model',async()=>{await nativeOperation({op:'removeModel',modelId:model.id});})}><Trash2 size={13}/>Remove</button>}{installed&&!loaded&&model.kind==='text'&&<button className="btn secondary" disabled={!!busy} onClick={()=>void work('Loading model',async()=>{await nativeOperation({op:'loadModel',modelId:model.id,jobId:job.current},progress);})}>Load</button>}{loaded&&<button className="btn secondary" disabled={!!busy} onClick={()=>void work('Unloading model',async()=>{await nativeOperation({op:'unloadModel'});})}>Unload</button>}</div></article>)}
 </section></div><section className="panel lab-panel"><h2>Generated artifacts</h2>{!artifacts.length&&<p>Generated work appears here with its model, seed, and provenance.</p>}<div className="artifact-grid">{artifacts.slice().reverse().slice(0,100).map(a=><article className="model-card" key={a.id}><strong>{a.prompt}</strong>{a.text?<p className="artifact-text">{a.text}</p>:a.asset?<AssetImage asset={a.asset}/>:null}<p>{a.model} · seed {a.seed}</p><details><summary>Provenance</summary><pre>{JSON.stringify(a,null,2)}</pre></details>{a.text&&<button className="btn secondary" disabled={!!busy} onClick={()=>void learnText(a)}>Learn as a text pattern</button>}{a.asset&&<button className="btn secondary" disabled={!!busy} onClick={()=>void work('Opening generated image',async()=>{const data=await callNative<number[]>({op:'asset',id:a.asset});await choose(new File([new Uint8Array(data)],`${a.id}.png`,{type:'image/png'}));})}>Inspect & learn image</button>}</article>)}</div></section></div>;
}
function AssetImage({asset}:{asset:string}){const[url,setUrl]=useState('');useEffect(()=>{let live=true;let url='';void callNative<number[]>({op:'asset',id:asset}).then(data=>{url=URL.createObjectURL(new Blob([new Uint8Array(data)],{type:'image/png'}));if(live)setUrl(url);else URL.revokeObjectURL(url);}).catch(()=>{if(live)setUrl('');});return()=>{live=false;URL.revokeObjectURL(url);};},[asset]);return url?<img className="generated-image" src={url} alt="Locally generated artifact"/>:null;}
